name: Demo - Data Tier Manager

on:
  workflow_dispatch:       # Manual trigger
  push:                    # Auto trigger on push/merge to main
    branches:
      - main

permissions:
  contents: write          # Needed to allow git push from workflow

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🧪 Copy sample config for demo (only for testing)
        run: cp sample/app_config.json .

      - name: 🔍 Step 1 - Read App Config
        id: config
        uses: ./actions/read-config

      - name: 🗂️ Step 2 - Fetch Table Metadata
        id: fetch
        uses: ./actions/fetch-metadata
        with:
          app_name: ${{ steps.config.outputs.app_name }}

      - name: 🧾 Step 3 - Generate JSON Files by Environment
        uses: ./actions/generate-json
        with:
          metadata: ${{ steps.fetch.outputs.metadata }}

      - name: 📂 Step 4 - Show Generated Files
        run: |
          echo "🗂 Contents of data-tier-snapshot:"
          ls -l data-tier-snapshot

          echo "📄 Sample: dev.json content:"
          cat data-tier-snapshot/dev.json

      - name: 💾 Step 5 - Commit and Push JSON Files (if changed)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

          git add data-tier-snapshot

          if ! git diff --cached --quiet; then
            echo "📤 Changes detected. Committing..."
            git commit -m "🧮 Add or update data-tier-snapshot JSON files"
            git push
          else
            echo "✅ No changes to commit."
          fi
