name: Demo - Data Tier Manager

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy Sample Config
        run: cp sample/app_config.json .

      - name: Read Config
        id: config
        uses: ./actions/read-config

      - name: Fetch Metadata
        id: fetch
        uses: ./actions/fetch-metadata
        with:
          app_name: ${{ steps.config.outputs.app_name }}

      - name: Generate JSON Files
        uses: ./actions/generate-json
        with:
          metadata: ${{ steps.fetch.outputs.metadata }}

      - name: Show Output Files
        run: |
          ls -l data-tier-snapshot
          cat data-tier-snapshot/dev.json
